LAB_01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('login/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls'))
]

accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    ]

webapp/urls.py
from django.urls import path

from .views.carts import CartAddView, CartIndexView, CartDeleteView
from .views.orders import OrderView, MyOrderView
from .views import ProductIndexView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

urlpatterns = [
    path('', ProductIndexView.as_view(), name="product_index"),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name="product_delete"),
    path('cart/product/<int:pk>/add', CartAddView.as_view(), name='cart_add'),
    path('cart/', CartIndexView.as_view(), name='cart_view'),
    path('cart/product/<int:pk>/delete', CartDeleteView.as_view(), name='cart_delete'),
    path('order/', OrderView.as_view(), name='order_view'),
    path('myorders/', MyOrderView.as_view(), name='my_order_view')
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

STATUS_CHOICES = [('other', 'Разное'), ('smartphone', 'Смартфон'), ('notebook', 'Ноутбук'), ('tv', 'Телевизор')]
User = get_user_model()


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    category = models.CharField(max_length=100,
                                choices=STATUS_CHOICES,
                                default=STATUS_CHOICES[0][0],
                                verbose_name='Категория')
    balance = models.IntegerField(verbose_name='Остаток')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")

    def __str__(self):
        return f'{self.pk}. {self.title}: {self.description}'

    class Meta:
        db_table = 'Products'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Order(models.Model):
    product = models.ForeignKey('webapp.Product',
                                on_delete=models.CASCADE,
                                verbose_name='Товар',
                                related_name='order')
    number = models.IntegerField(verbose_name='Количество товара')
    client = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               verbose_name='Клиент',
                               related_name='order',
                               null=True,
                               blank=True)

    class Meta:
        db_table = 'Orders'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from webapp.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []

    def clean_balance(self):
        balance = self.cleaned_data['balance']
        if balance < 0:
            raise ValidationError(
                f"Значение баланса должно быть больше нуля, '{balance}' не подходит")
        return balance


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Найти")

webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

from webapp.forms import ProductForm
from webapp.models import Product


def index_view(request):
    products = Product.objects.all().order_by('category', 'title').filter(balance__gt=0)
    return render(request, 'index_view.html', {'products': products})


def product_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'product_view.html', {'product': product})


def create_view(request):
    if request.method == 'GET':
        form = ProductForm()
        return render(request, 'product_create.html', {"form": form})
    else:
        form = ProductForm(data=request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')
            category = form.cleaned_data.get('category')
            balance = form.cleaned_data.get('balance')
            price = form.cleaned_data.get('price')
            new_task = Product.objects.create(title=title,
                                              description=description,
                                              category=category,
                                              balance=balance,
                                              price=price)
            return redirect('product_view', pk=new_task.pk)
        return render(request, 'product_create.html', {"form": form})


def update_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'GET':
        form = ProductForm(initial={
            'title': product.title,
            'description': product.description,
            'category': product.category,
            'balance': product.balance,
            'price': product.price
        })
        return render(request, 'product_update.html', {'form': form, 'product': product})
    else:
        form = ProductForm(data=request.POST)
        if form.is_valid():
            product.title = form.cleaned_data.get('title')
            product.description = form.cleaned_data.get('description')
            product.category = form.cleaned_data.get('category')
            product.balance = form.cleaned_data.get('balance')
            product.price = form.cleaned_data.get('price')
            product.save()
            return redirect('product_view', pk=product.pk)
        return render(request, 'product_update.html', {'form': form, 'product': product})


def delete_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'GET':
        return render(request, 'product_delete.html', {'product': product})
    else:
        product.delete()
        return redirect('index_view')

webapp/views/carts.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views import View

from webapp.models import Product


class CartAddView(View):
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs['pk'])
        if product.balance > 0:
            products = request.session.get('products', {})
            if products:
                if str(product.id) not in products.keys():
                    products[product.id] = 1
                else:
                    for item, value in products.items():
                        if value < product.balance:
                            if int(item) == product.id:
                                new_value = value+1
                                products[item] = new_value
            else:
                products[product.id] = 1
            request.session['products'] = products
        return redirect('product_index')


class CartIndexView(View):
    def get(self, request, *args, **kwargs):
        records = {}
        quantity = {}
        sum = {}
        total = 0
        products = request.session.get('products', {})
        product_ids = products.keys()
        new_products = Product.objects.filter(id__in=product_ids)
        for product in new_products:
            records[product.id] = product
            quantity[product.id] = products[str(product.id)]

        for key, value in records.items():
            for k, v in quantity.items():
                if value.id == k:
                    sum[value.id] = value.price*v
        for key, value in sum.items():
            total += value
        context = {
            'quantity': quantity,
            'records': records,
            'sum': sum,
            'total': total,
        }
        return render(request, 'carts/index.html', context)


class CartDeleteView(View):
    def post(self, request, *args, **kwargs):
        product_id = kwargs['pk']
        products = request.session.get('products', {})
        if products:
            products.pop(str(product_id))
        request.session['products'] = products
        return redirect('cart_view')

webapp/views/orders.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView

from webapp.models import Order, Product


class OrderView(View):
    def post(self, request, *args, **kwargs):
        products = request.session.get('products', {})
        print(products)
        product_ids = products.keys()
        new_products = Product.objects.filter(id__in=product_ids)
        for product in new_products:
            order = Order()
            if request.user.is_authenticated:
                order.client = request.user
            else:
                order.client = None
            order.product = product
            for k, v in products.items():
                if k == str(product.id):
                    order.number = v
                    product.balance = product.balance - v
                    product.save()
            order.save()

        products = {}
        request.session['products'] = products
        return render(request, 'order/index.html')


class MyOrderView(ListView):
    model = Order
    template_name = 'orders.html'
    permission_required = 'auth.view_user'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        objects = Order.objects.filter(client_id=self.request.user.id)
        context["objects"] = objects
        return context

webapp/views/products.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import DeleteView, DetailView, ListView, CreateView, UpdateView

from webapp.forms import ProductForm, SearchForm
from webapp.models import Product


class ProductIndexView(ListView):
    model = Product
    template_name = 'products/index.html'
    context_object_name = 'products'
    paginate_by = 5
    paginate_orphans = 0

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(title__icontains=self.search_value) | Q(category__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.filter(balance__gt=0).order_by('category', 'title')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm()
        if self.search_value:
            context['form'] = SearchForm(initial={"search": self.search_value})
            context['search'] = self.search_value
        return context

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/view.html'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "products/create.html"
    permission_required = 'webapp.add_product'

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "products/update.html"
    permission_required = 'webapp.change_product'

    def get_success_url(self):
        return reverse('product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'products/delete.html'
    permission_required = 'webapp.delete_product'

    def get_success_url(self):
        return reverse('product_index')

webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href={% url 'product_index' %}>Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% block nav %}
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href={% url 'accounts:login' %}?next={{ request.get_full_path }}>Вход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   href={% url 'accounts:create' %}?next={{ request.get_full_path }}>Регистрация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href='{% url 'cart_view' %}'>Открыть корзину</a>
                            </li>
                        {% else %}
                            {% if perms.webapp.add_product %}
                                <li class="nav-item">
                                    <a class="nav-link" href={% url 'product_create' %}>Создать продукт</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href='{% url 'cart_view' %}'>Открыть корзину</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href='{% url 'my_order_view' %}'>История заказов</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'accounts:detail' user.pk %}">Привет {{ user.username }}!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href={% url 'accounts:logout' %}?next={{ request.get_full_path }}>Выход</a>
                            </li>
                        {% endif %}
                    {% endblock %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

webapp/templates/index_view.html
{% extends 'base.html' %}

{% block title %}
Products
{% endblock %}

{% block content %}
        <div class="mb-4">
            <h2 class="text-success">Текущие Записи</h2>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 justify-content-center">
            {% for product in products %}
                <div class="col my-2">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Категория: {{ product.get_category_display }}</h6>
                            <p class="card-text">Цена: {{ product.price }}</p>
                            <a href="{% url 'product_view' product.pk %}" class="card-link">Подробнее...</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

webapp/templates/orders.html
{% extends 'base.html' %}

{% block content %}
<div class="my-4">
        <h2 class="text-success text-center">История заказов</h2>
    </div>
    <div class="mt-5">
        <table class="table mb-4">
            <thead>
            <tr>
                <th scope="col">Товар</th>
                <th scope="col">Количество</th>
            </tr>
            </thead>
            <tbody>
            {% for object in objects %}
                <tr>
                    <td>{{ object.product.title }}</td>
                    <td>{{ object.number }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

webapp/templates/product_create.html
{% extends 'base.html' %}

{% block title %}
    Создание новой записи
{% endblock %}

{% block nav %}

{% endblock %}

{% block  content %}
<div class="container">
        <div class="text-center my-5">
            <h1 class="text-success">Создание новой записи</h1>
        </div>
        <div>
            <form method="post">
                {% include 'partial/form.html' with button_text='Создать' %}
            </form>
        </div>
        <div class="my-3">
            <a class="btn btn-danger w-100" href={% url 'index_view' %}>Отмена</a>
        </div>
    </div>
{% endblock %}

webapp/templates/product_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <h2 class="text-alert">Удалить задачу "{{ product.title }}"</h2>
            <input class="btn btn-danger w-100 mt-4" type="submit" value="Да">
            </form>
        <a class="my-3 btn btn-success w-100" href="{% url "product_view" product.pk %}">Нет</a>
    </div>

{% endblock %}

webapp/templates/product_update.html
{% extends 'base.html' %}

{% block title %}
    Редактирование записи
{% endblock %}

{% block nav %}

{% endblock %}

{% block  content %}
<div class="container">
        <div class="text-center my-5">
            <h1 class="text-success">Редактирование записи</h1>
        </div>
        <div>
            <form method="post">
                {% include 'partial/form.html' with button_text='Изменить' %}
            </form>
        </div>
        <div class="my-3">
            <a class="btn btn-danger w-100" href={% url 'index_view' %}>Отмена</a>
        </div>
    </div>
{% endblock %}

webapp/templates/product_view.html
{% extends 'base.html' %}

{% block title %}
Product {{ product.pk }}
{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href='{% url 'create_view' %}'>Создать запись</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href='{% url 'update_view' product.pk %}'>Редактировать запись</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-danger" href="{% url 'delete_view' product.pk %}">Удалить запись</a>
    </li>
{% endblock %}

{% block content %}
        <div class="text-center my-5">
            <h1 class="text-success"> Просмотр записи №{{ product.id }}</h1>
        </div>
        <div class="alert alert-success" role="alert">
            <h6>Наименование товара: {{ product.title }}</h6>
            <h6>Категория товара: {{ product.get_category_display }}</h6>
            <p>Остаток: {{ product.balance }}</p>
            <p>Цена: {{ product.price }}</p>
            {% if product.description%}
                <p>Описание товара: {{ product.description }}</p>
            {% else %}
                <p>Описание товара: НЕТ</p>
            {% endif %}
        </div>
{% endblock %}